# See https://symfony.com/doc/current/email/dev_environment.html
swiftmailer:
    # send all emails to a specific address
    delivery_addresses: ['pablosik2@gmail.com']
#    delivery_whitelist:
#        - '/@special\.com$/'
